name: Node.js Package

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'Version to release'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          
  release:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ inputs.version != '' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Configure GIT
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Release
        run: npm version ${{ github.event.inputs.version }}

      - name: Push changes
        run: git push --follow-tags

      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
      
